[package]
name = "cpu-game"
version = "0.0.1"
edition = "2021"
description = "A small CPU game to play with fictional hardware."
license = "CC-BY-NC-ND-4.0"

[dependencies]
colored = "2.1.0"
dialoguer = "0.11.0"
serde = { version = "1.0.207", features = ["derive"] }
toml = "0.8.19"
